package io.openactors4j.core.impl.common;

public enum InstanceState {
  NEW,
  CREATING,
  CREATE_DELAYED,
  CREATE_FAILED,
  STARTING,
  START_FAILED,
  RUNNING,
  PROCESSING_FAILED,
  RESTARTING,
  RESTARTING_FAILED,
  STOPPING,
  STOPPED;
//  RESTARTING_DELAYED,
//   DELAYED,
//  SUSPENDED;
}
